# Generated by Django 3.2.8 on 2021-10-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
