# Generated by Django 3.2.9 on 2021-11-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0003_rename_application_id_version_application_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='teams_url',
            field=models.URLField(max_length=1500),
        ),
    ]
