# Generated by Django 3.2.9 on 2021-11-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs_app', '0004_alter_application_teams_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='teams_url',
            field=models.CharField(max_length=1500),
        ),
    ]
